### ISSUE TITLE
Compilation error with TypeScript 2.4

### ISSUE THREAD

**Issue by mareklinka** [Microsoft/vss-web-extension-sdk#50]
I tried to make use of this lib while having the latest TypeScript installed and the sources cannot be compiled. running into the following compilation issues:

```
node_modules/@types/react/index.d.ts(165,11): error TS2559: Type 'Component<P, S>' has no properties in common with type 'ComponentLifecycle<P, S>'.
typings/vss.d.ts(3463,14): error TS2559: Type 'TemplateViewModel' has no properties in common with type 'EnhancementOptions'.
typings/vss.d.ts(9965,14): error TS2415: Class 'ComboDateBehavior' incorrectly extends base class 'BaseComboBehavior'.
  Types of property 'getValue' are incompatible.
    Type '() => Date' is not assignable to type '<TValue>() => TValue'.
      Type 'Date' is not assignable to type 'TValue'.
typings/vss.d.ts(10050,14): error TS2415: Class 'ComboMultiValueBehavior' incorrectly extends base class 'ComboListBehavior'.
  Types of property 'getValue' are incompatible.
    Type '() => string[]' is not assignable to type '<TValue>() => TValue'.
      Type 'string[]' is not assignable to type 'TValue'.
typings/vss.d.ts(10224,14): error TS2417: Class static side 'typeof DialogO' incorrectly extends base class static side 'typeof AjaxPanelO'.
  Types of property 'create' are incompatible.
    Type '<T extends Dialog>(dialogType: new (options: any) => T, options?: any) => T' is not assignable to type '<TControl extends Control<any>, TOptions>(controlType: new (options: TOptions) => TControl, c
onta...'.
      Types of parameters 'dialogType' and 'controlType' are incompatible.
        Type 'new (options: TOptions) => TControl' is not assignable to type 'new (options: any) => Dialog'.
          Type 'TControl' is not assignable to type 'Dialog'.
            Type 'Control<any>' is not assignable to type 'Dialog'.
              Property '_specifiedMaxWidth' is missing in type 'Control<any>'.
```

I can confirm that with TypeScript versions 2.2.1 - 2.3 it works without issues. Could the lib be updated? If not, it might be a good thing to mentioned this in the readme.

**Comment by MrTarantula** [comment]
At least part of this is the same problem I have in #48. The `incorrectly extends` errors can be fixed by changing the access modifiers of those properties. No response yet on my issue so it makes me wonder if anybody is paying attention.

**Comment by MrTarantula** [comment]
I started getting more errors like yours after cloning my extension to a new machine. I moved my code to the [ALM Rangers' webpack-based Yeoman generator](https://github.com/ALM-Rangers/generator-team-services-extension) and have had no issues cloning on new machines. It took a bit of finagling with webpack to get everything set up, and of course all paths in `vss-extension.json` and html files need to be updated.

I didn't look into why I was getting the errors, I'm just happy to have it fixed.

**Comment by mosheco** [comment]
Any news here?
Alternatively, how do I downgrade to use Typescript 2.3 ?

**Comment by trevorsg** [comment]
It will be a few weeks before we have a 2.4 update. Certainly you can downgrade. If you're using npm, just run `npm install --global typescript@2.3.4`.

**Comment by onlyutkarsh** [comment]
Any update on this defect? I am seeing this issue wherein [breakpoints jump wildly within vs code](https://github.com/Microsoft/vscode-chrome-debug/issues/528).  This is similar to issue [378](https://github.com/Microsoft/vscode-chrome-debug/issues/378) on vs code's chrome debugger, and the resolution is to [upgrade the TS version to 2.4+](https://github.com/Microsoft/vscode-chrome-debug/issues/378#issuecomment-309508427). Any update on this will be highly appreciated!

**Comment by knom** [comment]
Is there any update on this?
Typescript 2.4 is the default on VSTS now.. Which means my build will always fail :-(

**Comment by trevorsg** [comment]
Master has a dependency on TypeScript 2.5.3, which is the version used in VSTS, so this should already be resolved. Let me know if there are still issues here.

**Comment by knom** [comment]
I'm using the latest versoin of https://www.npmjs.com/package/vss-web-extension-sdk
It's not fixed there..

**Comment by trevorsg** [comment]
Ah, npm did not get updated... neat. Let's fix that.

**Comment by trevorsg** [comment]
I updated the minor version, but it should have been fine as is. In other words, 4.126.0 should be the same as 4.125.2. Looking at the tree for v4.125.2 the TypeScript dependency is 2.5.3.

**Comment by knom** [comment]
Works for me now!
Thanks!

**Comment by trevorsg** [comment]
Great to hear!
